name: Deploy to Server

on:
  push:
    branches:
      - live

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up SSH
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.Private_Key }}" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa
          ssh-keyscan -H ${{ secrets.VPS_IP }} >> ~/.ssh/known_hosts

      # SSH into the server and run deployment commands
      - name: Deploy application
        run: |
          ssh -i ~/.ssh/id_rsa ${{secrets.VPS_User}}@${{secrets.VPS_IP}} << 'EOF'
            TARGET_DIR="$HOME/projects/SolutionNamePlaceholder"

            if [ -d "$TARGET_DIR" ]; then
              cd "$TARGET_DIR"
              git pull origin live
              docker compose down
            else
              mkdir -p "$HOME/projects"
              git clone -b live your-user:your-user/SolutionNamePlaceholder.git $TARGET_DIR
              cd "$TARGET_DIR"
            fi
            
            docker-compose build
            docker-compose up -d 
          EOF
